import type { Patient, Appointment, Transaction } from './types';

export const mockPatients: Patient[] = [
  {
    _id: '1',
    patientName: 'Ahmed Ali',
    patientId: 'P001',
    dateOfBirth: '1995-08-22',
    phone: '+963 912 345 678',
    email: 'ahmed.ali@example.com',
    address: '123 Damascus Street, Syria',
    startDate: new Date('2023-01-15').toISOString(),
    currentStatus: 'Active Treatment',
    totalSessions: 24,
    completedSessions: 10,
    chiefComplaint: 'Crowding in lower arch and crossbite.',
    notes: 'Patient is responsive to treatment. Minor adjustments needed.',
    avatarUrl: 'https://placehold.co/100x100.png',
  },
  {
    _id: '2',
    patientName: 'Fatima Zahra',
    patientId: 'P002',
    dateOfBirth: '2001-03-10',
    phone: '+963 998 765 432',
    email: 'fatima.zahra@example.com',
    address: '456 Aleppo Avenue, Syria',
    startDate: new Date('2023-03-20').toISOString(),
    currentStatus: 'Active Treatment',
    totalSessions: 30,
    completedSessions: 5,
    chiefComplaint: 'Overjet and spacing issues.',
    notes: 'Initial phase of treatment. Patient reports mild discomfort.',
    avatarUrl: 'https://placehold.co/100x100.png',
  },
  {
    _id: '3',
    patientName: 'Youssef El-Masry',
    patientId: 'P003',
    dateOfBirth: '1988-11-05',
    phone: '+963 945 678 123',
    email: 'youssef.masry@example.com',
    address: '789 Homs Boulevard, Syria',
    startDate: new Date('2022-11-01').toISOString(),
    currentStatus: 'Final Phase',
    totalSessions: 18,
    completedSessions: 15,
    chiefComplaint: 'Deep bite and minor rotations.',
    notes: 'Approaching end of treatment. Excellent progress.',
    avatarUrl: 'https://placehold.co/100x100.png',
  },
    {
    _id: '4',
    patientName: 'Mariam Ibrahim',
    patientId: 'P004',
    dateOfBirth: '1999-05-12',
    phone: '+963 933 112 233',
    email: 'mariam.ibrahim@example.com',
    address: '101 Latakia Corniche, Syria',
    startDate: new Date('2023-05-10').toISOString(),
    currentStatus: 'Active Treatment',
    totalSessions: 20,
    completedSessions: 2,
    chiefComplaint: 'Aesthetic concerns regarding front teeth alignment.',
    notes: 'New patient, first adjustment completed.',
    avatarUrl: 'https://placehold.co/100x100.png',
  },
    {
    _id: '5',
    patientName: 'Khalid Hassan',
    patientId: 'P005',
    dateOfBirth: '1992-09-30',
    phone: '+963 955 444 555',
    email: 'khalid.hassan@example.com',
    address: '212 Tartus Port Road, Syria',
    startDate: new Date('2021-08-19').toISOString(),
    currentStatus: 'Retention Phase',
    totalSessions: 24,
    completedSessions: 24,
    chiefComplaint: 'Initial severe crowding.',
    notes: 'Treatment complete. Now in retention phase.',
    avatarUrl: 'https://placehold.co/100x100.png',
  },
];

export const mockAppointments: Appointment[] = [
  {
    _id: 'apt1',
    patientId: 'P001',
    status: 'Waiting',
    queueTime: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    _id: 'apt2',
    patientId: 'P002',
    status: 'Waiting',
    queueTime: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
    {
    _id: 'apt3',
    patientId: 'P003',
    status: 'Waiting',
    queueTime: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  },
];

export const mockTransactions: Transaction[] = [
  {
    _id: 'txn1',
    patientId: 'P001',
    patientName: 'Ahmed Ali',
    date: new Date('2024-05-20').toISOString(),
    description: 'Monthly treatment fee',
    amount: 150.00,
    type: 'Charge',
    status: 'Pending',
  },
  {
    _id: 'txn2',
    patientId: 'P002',
    patientName: 'Fatima Zahra',
    date: new Date('2024-05-22').toISOString(),
    description: 'Down payment',
    amount: 500.00,
    type: 'Payment',
    status: 'Paid',
  },
  {
    _id: 'txn3',
    patientId: 'P003',
    patientName: 'Youssef El-Masry',
    date: new Date('2024-05-18').toISOString(),
    description: 'Adjustment session',
    amount: 100.00,
    type: 'Charge',
    status: 'Paid',
  },
  {
    _id: 'txn4',
    patientId: 'P001',
    patientName: 'Ahmed Ali',
    date: new Date('2024-04-20').toISOString(),
    description: 'Monthly treatment fee',
    amount: 150.00,
    type: 'Charge',
    status: 'Paid',
  },
    {
    _id: 'txn5',
    patientId: 'P004',
    patientName: 'Mariam Ibrahim',
    date: new Date('2024-05-10').toISOString(),
    description: 'Initial consultation',
    amount: 250.00,
    type: 'Payment',
    status: 'Paid',
  },
];
